{
 "title": "Mongo Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mongo Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "localTime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "uptime",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "network.serviceExecutorTaskStats.threadsRunning:*",
     "timeField": "localTime"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "localTime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "connections.current",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "network.serviceExecutorTaskStats.threadsRunning:*",
     "timeField": "localTime"
    }
   ]
  },
  {
   "title": "Active Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "localTime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "globalLock.activeClients.total",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "network.serviceExecutorTaskStats.threadsRunning:*",
     "timeField": "localTime"
    }
   ]
  },
  {
   "title": "Avg Object Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "localTime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "avgObjSize",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "localTime"
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "localTime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "dataSize",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "dataSize:*",
     "timeField": "localTime"
    }
   ]
  },
  {
   "title": "Objects created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "localTime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "objects",
       "id": "1",
       "meta": {
        "std_deviation": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "timeField": "localTime"
    }
   ]
  },
  {
   "title": "Ping Response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "localTime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metrics.commands.ping.total",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "network.serviceExecutorTaskStats.threadsRunning:*",
     "timeField": "localTime"
    }
   ]
  },
  {
   "title": "Documents returned",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "localTime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metrics.document.returned",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "localTime"
    }
   ]
  },
  {
   "title": "Running Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "localTime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "network.serviceExecutorTaskStats.threadsRunning",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "network.serviceExecutorTaskStats.threadsRunning:*",
     "timeField": "localTime"
    }
   ]
  }
 ]
}