#!/bin/bash
#
#       /etc/rc.d/init.d/<servicename>
#
#       <description of the *service*>
#       <any general comments about this init script>
#
# <tags -- see below for tag definitions.  *Every line* from the top
#  of the file to the end of the tags section must begin with a #
#  character.  After the tags section, there should be a blank line.
#  This keeps normal comments in the rest of the file from being
#  mistaken for tags, should they happen to fit the pattern.>

# Source function library.
. /etc/init.d/functions
PROGNAME="api_wsgi"
NAME="cuckooapi"
DROPUSER="CUCKOO_USER"
MYHOMEDIR="CUCKOODIR/utils"
LOGFILE="/var/log/cuckoo/api.log"
OPTIONS="-w 16 --bind 127.0.0.1:8090"

start() {
        echo "Starting $PROGNAME: "
	su - $DROPUSER -c "cd $MYHOMEDIR ; gunicorn $OPTIONS $PROGNAME >> $LOGFILE 2>&1 &"
}

stop() {
        echo "Shutting down $PROGNAME: "
	ps -ef|grep $PROGNAME|grep $DROPUSER|grep -v grep|awk '{print $2}'|while read line; do kill $line;done
}
status() {
	C=`ps -ef|grep $PROGNAME|grep -v grep`
	if [ -n "$C" ]; then
		echo "$NAME is running"
	else
		echo "$NAME is *NOT* running"
	fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
	status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: <servicename> {start|stop|status|reload|restart[|probe]"
        exit 1
        ;;
esac
exit $?
